services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: coreedificio-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "CoreEdificio!2025#StrongPass1"
    ports:
      - "1433:1433"
    volumes:
      - coreedificio_sql_data:/var/opt/mssql

volumes:
  coreedificio_sql_data:
